kafka:
  address: 172.31.10.154:9092
  seeds: twitter.top20.seeds
  pages: twitter.top20.pages
  links: twitter.top20.links
  fails: twitter.top20.fails
  consume_group: fetcher1

seed_list: top20_account.txt

zookeeper: 172.31.24.55:2181
