kafka:
  address: 172.31.10.154:9092
  seeds: t.seeds.test
  pages: t.pages.test
  links: t.links.test
  fails: t.fails.test
  consume_group: fetcher

seed_list: top20_account.txt

zookeeper: 172.31.24.55:2181
